/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.game;
import java.awt.Color;
import my.setup.*;
import my.homeScreen.*;
import static java.awt.Color.red;
import static java.awt.Color.green;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.*;
import java.util.Random;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicToggleButtonUI;

/**
 *
 * @author kshar1
 */
public class game extends javax.swing.JFrame {
    
    private final int wordLength;
    private String word;
    private String[] wordToGuess;
    private final JTextField[] letters = new JTextField[17];
    private int mistakeCount;
    private boolean[] canEnable=new boolean[26];
    private final JToggleButton[] letterButtons = new JToggleButton[26];
    private final String[] alphabet={"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"};
    private int correctLetters;
    private int guessCount=0;
    private ImageIcon[] images ={new ImageIcon(new ImageIcon("src/my/game/hangedMan/zero.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),new ImageIcon(new ImageIcon("src/my/game/hangedMan/one.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),
                                new ImageIcon(new ImageIcon("src/my/game/hangedMan/two.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),new ImageIcon(new ImageIcon("src/my/game/hangedMan/three.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),
                                new ImageIcon(new ImageIcon("src/my/game/hangedMan/four.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),new ImageIcon(new ImageIcon("src/my/game/hangedMan/five.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT)),
                                new ImageIcon(new ImageIcon("src/my/game/hangedMan/dead.png").getImage().getScaledInstance(320, 180, Image.SCALE_DEFAULT))};
    
    public game(int wL) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        wordLength=wL;
        JToggleButton[] letterButtons01={aButton, bButton, cButton, dButton, eButton, fButton, gButton,
                                            hButton, iButton, jButton, kButton, lButton, mButton, nButton,
                                            oButton, pButton, qButton, rButton, sButton, tButton, uButton,
                                            vButton, wButton, xButton, yButton, zButton};
        JTextField[] letters01={letter1, letter2, letter3, letter4, letter5, letter6, letter7, letter8, 
                                letter9, letter10, letter11, letter12, letter13};
        
        for(int x=0; x<=12;x++)
            letters[x]=letters01[x];
        for(int x=0; x<=25;x++)
            letterButtons[x]=letterButtons01[x];
        for(int x=0;x<=25;x++)
            canEnable[x]=true;
        hangedMan.setIcon(images[mistakeCount]);
        endScreen.setBackground(Color.darkGray);
        gameEnd.setBackground(Color.darkGray);
        endScreen.setVisible(false);
        gameEnd.setVisible(false);
        this.getContentPane().setBackground(Color.darkGray);
        wordSelect();
        wordArray();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton = new javax.swing.JToggleButton();
        kButton = new javax.swing.JToggleButton();
        fButton = new javax.swing.JToggleButton();
        hButton = new javax.swing.JToggleButton();
        bButton = new javax.swing.JToggleButton();
        cButton = new javax.swing.JToggleButton();
        rButton = new javax.swing.JToggleButton();
        eButton = new javax.swing.JToggleButton();
        mButton = new javax.swing.JToggleButton();
        uButton = new javax.swing.JToggleButton();
        zButton = new javax.swing.JToggleButton();
        gButton = new javax.swing.JToggleButton();
        oButton = new javax.swing.JToggleButton();
        pButton = new javax.swing.JToggleButton();
        iButton = new javax.swing.JToggleButton();
        qButton = new javax.swing.JToggleButton();
        lButton = new javax.swing.JToggleButton();
        aButton = new javax.swing.JToggleButton();
        nButton = new javax.swing.JToggleButton();
        wButton = new javax.swing.JToggleButton();
        dButton = new javax.swing.JToggleButton();
        xButton = new javax.swing.JToggleButton();
        tButton = new javax.swing.JToggleButton();
        yButton = new javax.swing.JToggleButton();
        vButton = new javax.swing.JToggleButton();
        sButton = new javax.swing.JToggleButton();
        letter1 = new javax.swing.JTextField();
        letter2 = new javax.swing.JTextField();
        letter3 = new javax.swing.JTextField();
        letter4 = new javax.swing.JTextField();
        letter5 = new javax.swing.JTextField();
        letter6 = new javax.swing.JTextField();
        letter7 = new javax.swing.JTextField();
        letter8 = new javax.swing.JTextField();
        letter9 = new javax.swing.JTextField();
        letter10 = new javax.swing.JTextField();
        letter11 = new javax.swing.JTextField();
        mistakeCounter = new javax.swing.JLabel();
        letter12 = new javax.swing.JTextField();
        letter13 = new javax.swing.JTextField();
        gameEnd = new javax.swing.JPanel();
        leaderboard = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usernameInput = new javax.swing.JTextPane();
        submit = new javax.swing.JButton();
        endScreen = new javax.swing.JPanel();
        stats = new javax.swing.JTextArea();
        endText = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        hangedMan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(java.awt.Color.black);
        back.setForeground(java.awt.Color.white);
        back.setText("Play Again");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(70, 70, 70));

        jButton.setBackground(java.awt.Color.black);
        jButton.setForeground(java.awt.Color.white);
        jButton.setText("J");
        jButton.setToolTipText("");
        jButton.setBorder(null);
        jButton.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        kButton.setBackground(java.awt.Color.black);
        kButton.setForeground(java.awt.Color.white);
        kButton.setText("K");
        kButton.setToolTipText("");
        kButton.setBorder(null);
        kButton.setMaximumSize(new java.awt.Dimension(30, 30));
        kButton.setMinimumSize(new java.awt.Dimension(30, 30));
        kButton.setPreferredSize(new java.awt.Dimension(40, 40));
        kButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonMouseClicked(evt);
            }
        });
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });

        fButton.setBackground(java.awt.Color.black);
        fButton.setForeground(java.awt.Color.white);
        fButton.setText("F");
        fButton.setToolTipText("");
        fButton.setBorder(null);
        fButton.setMaximumSize(new java.awt.Dimension(30, 30));
        fButton.setMinimumSize(new java.awt.Dimension(30, 30));
        fButton.setPreferredSize(new java.awt.Dimension(40, 40));
        fButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButtonMouseClicked(evt);
            }
        });
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });

        hButton.setBackground(java.awt.Color.black);
        hButton.setForeground(java.awt.Color.white);
        hButton.setText("H");
        hButton.setToolTipText("");
        hButton.setBorder(null);
        hButton.setMaximumSize(new java.awt.Dimension(30, 30));
        hButton.setMinimumSize(new java.awt.Dimension(30, 30));
        hButton.setPreferredSize(new java.awt.Dimension(40, 40));
        hButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hButtonMouseClicked(evt);
            }
        });
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });

        bButton.setBackground(java.awt.Color.black);
        bButton.setForeground(java.awt.Color.white);
        bButton.setText("B");
        bButton.setToolTipText("");
        bButton.setBorder(null);
        bButton.setMaximumSize(new java.awt.Dimension(30, 30));
        bButton.setMinimumSize(new java.awt.Dimension(30, 30));
        bButton.setPreferredSize(new java.awt.Dimension(40, 40));
        bButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bButtonMouseClicked(evt);
            }
        });
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        cButton.setBackground(java.awt.Color.black);
        cButton.setForeground(java.awt.Color.white);
        cButton.setText("C");
        cButton.setToolTipText("");
        cButton.setBorder(null);
        cButton.setMaximumSize(new java.awt.Dimension(30, 30));
        cButton.setMinimumSize(new java.awt.Dimension(30, 30));
        cButton.setPreferredSize(new java.awt.Dimension(40, 40));
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cButtonMouseClicked(evt);
            }
        });
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        rButton.setBackground(java.awt.Color.black);
        rButton.setForeground(java.awt.Color.white);
        rButton.setText("R");
        rButton.setToolTipText("");
        rButton.setBorder(null);
        rButton.setMaximumSize(new java.awt.Dimension(30, 30));
        rButton.setMinimumSize(new java.awt.Dimension(30, 30));
        rButton.setPreferredSize(new java.awt.Dimension(40, 40));
        rButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rButtonMouseClicked(evt);
            }
        });
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });

        eButton.setBackground(java.awt.Color.black);
        eButton.setForeground(java.awt.Color.white);
        eButton.setText("E");
        eButton.setToolTipText("");
        eButton.setBorder(null);
        eButton.setMaximumSize(new java.awt.Dimension(30, 30));
        eButton.setMinimumSize(new java.awt.Dimension(30, 30));
        eButton.setPreferredSize(new java.awt.Dimension(40, 40));
        eButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eButtonMouseClicked(evt);
            }
        });
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });

        mButton.setBackground(java.awt.Color.black);
        mButton.setForeground(java.awt.Color.white);
        mButton.setText("M");
        mButton.setToolTipText("");
        mButton.setBorder(null);
        mButton.setMaximumSize(new java.awt.Dimension(30, 30));
        mButton.setMinimumSize(new java.awt.Dimension(30, 30));
        mButton.setPreferredSize(new java.awt.Dimension(40, 40));
        mButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mButtonMouseClicked(evt);
            }
        });
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });

        uButton.setBackground(java.awt.Color.black);
        uButton.setForeground(java.awt.Color.white);
        uButton.setText("U");
        uButton.setToolTipText("");
        uButton.setBorder(null);
        uButton.setMaximumSize(new java.awt.Dimension(30, 30));
        uButton.setMinimumSize(new java.awt.Dimension(30, 30));
        uButton.setPreferredSize(new java.awt.Dimension(40, 40));
        uButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uButtonMouseClicked(evt);
            }
        });
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });

        zButton.setBackground(java.awt.Color.black);
        zButton.setForeground(java.awt.Color.white);
        zButton.setText("Z");
        zButton.setToolTipText("");
        zButton.setBorder(null);
        zButton.setMaximumSize(new java.awt.Dimension(30, 30));
        zButton.setMinimumSize(new java.awt.Dimension(30, 30));
        zButton.setPreferredSize(new java.awt.Dimension(40, 40));
        zButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zButtonMouseClicked(evt);
            }
        });
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });

        gButton.setBackground(java.awt.Color.black);
        gButton.setForeground(java.awt.Color.white);
        gButton.setText("G");
        gButton.setToolTipText("");
        gButton.setBorder(null);
        gButton.setMaximumSize(new java.awt.Dimension(30, 30));
        gButton.setMinimumSize(new java.awt.Dimension(30, 30));
        gButton.setPreferredSize(new java.awt.Dimension(40, 40));
        gButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gButtonMouseClicked(evt);
            }
        });
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });

        oButton.setBackground(java.awt.Color.black);
        oButton.setForeground(java.awt.Color.white);
        oButton.setText("O");
        oButton.setToolTipText("");
        oButton.setBorder(null);
        oButton.setMaximumSize(new java.awt.Dimension(30, 30));
        oButton.setMinimumSize(new java.awt.Dimension(30, 30));
        oButton.setPreferredSize(new java.awt.Dimension(40, 40));
        oButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oButtonMouseClicked(evt);
            }
        });
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });

        pButton.setBackground(java.awt.Color.black);
        pButton.setForeground(java.awt.Color.white);
        pButton.setText("P");
        pButton.setToolTipText("");
        pButton.setBorder(null);
        pButton.setMaximumSize(new java.awt.Dimension(30, 30));
        pButton.setMinimumSize(new java.awt.Dimension(30, 30));
        pButton.setPreferredSize(new java.awt.Dimension(40, 40));
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pButtonMouseClicked(evt);
            }
        });
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });

        iButton.setBackground(java.awt.Color.black);
        iButton.setForeground(java.awt.Color.white);
        iButton.setText("I");
        iButton.setToolTipText("");
        iButton.setBorder(null);
        iButton.setMaximumSize(new java.awt.Dimension(30, 30));
        iButton.setMinimumSize(new java.awt.Dimension(30, 30));
        iButton.setPreferredSize(new java.awt.Dimension(40, 40));
        iButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iButtonMouseClicked(evt);
            }
        });
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });

        qButton.setBackground(java.awt.Color.black);
        qButton.setForeground(java.awt.Color.white);
        qButton.setText("Q");
        qButton.setToolTipText("");
        qButton.setBorder(null);
        qButton.setMaximumSize(new java.awt.Dimension(30, 30));
        qButton.setMinimumSize(new java.awt.Dimension(30, 30));
        qButton.setPreferredSize(new java.awt.Dimension(40, 40));
        qButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qButtonMouseClicked(evt);
            }
        });
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });

        lButton.setBackground(java.awt.Color.black);
        lButton.setForeground(java.awt.Color.white);
        lButton.setText("L");
        lButton.setToolTipText("");
        lButton.setBorder(null);
        lButton.setMaximumSize(new java.awt.Dimension(30, 30));
        lButton.setMinimumSize(new java.awt.Dimension(30, 30));
        lButton.setPreferredSize(new java.awt.Dimension(40, 40));
        lButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lButtonMouseClicked(evt);
            }
        });
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        aButton.setBackground(java.awt.Color.black);
        aButton.setForeground(java.awt.Color.white);
        aButton.setText("A");
        aButton.setToolTipText("");
        aButton.setBorder(null);
        aButton.setMaximumSize(new java.awt.Dimension(30, 30));
        aButton.setMinimumSize(new java.awt.Dimension(30, 30));
        aButton.setPreferredSize(new java.awt.Dimension(40, 40));
        aButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aButtonMouseClicked(evt);
            }
        });
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });

        nButton.setBackground(java.awt.Color.black);
        nButton.setForeground(java.awt.Color.white);
        nButton.setText("N");
        nButton.setToolTipText("");
        nButton.setBorder(null);
        nButton.setMaximumSize(new java.awt.Dimension(30, 30));
        nButton.setMinimumSize(new java.awt.Dimension(30, 30));
        nButton.setPreferredSize(new java.awt.Dimension(40, 40));
        nButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nButtonMouseClicked(evt);
            }
        });
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });

        wButton.setBackground(java.awt.Color.black);
        wButton.setForeground(java.awt.Color.white);
        wButton.setText("W");
        wButton.setToolTipText("");
        wButton.setBorder(null);
        wButton.setMaximumSize(new java.awt.Dimension(30, 30));
        wButton.setMinimumSize(new java.awt.Dimension(30, 30));
        wButton.setPreferredSize(new java.awt.Dimension(40, 40));
        wButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wButtonMouseClicked(evt);
            }
        });
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });

        dButton.setBackground(java.awt.Color.black);
        dButton.setForeground(java.awt.Color.white);
        dButton.setText("D");
        dButton.setToolTipText("");
        dButton.setBorder(null);
        dButton.setMaximumSize(new java.awt.Dimension(30, 30));
        dButton.setMinimumSize(new java.awt.Dimension(30, 30));
        dButton.setPreferredSize(new java.awt.Dimension(40, 40));
        dButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dButtonMouseClicked(evt);
            }
        });
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });

        xButton.setBackground(java.awt.Color.black);
        xButton.setForeground(java.awt.Color.white);
        xButton.setText("X");
        xButton.setToolTipText("");
        xButton.setBorder(null);
        xButton.setMaximumSize(new java.awt.Dimension(30, 30));
        xButton.setMinimumSize(new java.awt.Dimension(30, 30));
        xButton.setPreferredSize(new java.awt.Dimension(40, 40));
        xButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xButtonMouseClicked(evt);
            }
        });
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });

        tButton.setBackground(java.awt.Color.black);
        tButton.setForeground(java.awt.Color.white);
        tButton.setText("T");
        tButton.setToolTipText("");
        tButton.setBorder(null);
        tButton.setMaximumSize(new java.awt.Dimension(30, 30));
        tButton.setMinimumSize(new java.awt.Dimension(30, 30));
        tButton.setPreferredSize(new java.awt.Dimension(40, 40));
        tButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tButtonMouseClicked(evt);
            }
        });
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });

        yButton.setBackground(java.awt.Color.black);
        yButton.setForeground(java.awt.Color.white);
        yButton.setText("Y");
        yButton.setToolTipText("");
        yButton.setBorder(null);
        yButton.setMaximumSize(new java.awt.Dimension(30, 30));
        yButton.setMinimumSize(new java.awt.Dimension(30, 30));
        yButton.setPreferredSize(new java.awt.Dimension(40, 40));
        yButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yButtonMouseClicked(evt);
            }
        });
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });

        vButton.setBackground(java.awt.Color.black);
        vButton.setForeground(java.awt.Color.white);
        vButton.setText("V");
        vButton.setToolTipText("");
        vButton.setBorder(null);
        vButton.setMaximumSize(new java.awt.Dimension(30, 30));
        vButton.setMinimumSize(new java.awt.Dimension(30, 30));
        vButton.setPreferredSize(new java.awt.Dimension(40, 40));
        vButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vButtonMouseClicked(evt);
            }
        });
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });

        sButton.setBackground(java.awt.Color.black);
        sButton.setForeground(java.awt.Color.white);
        sButton.setText("S");
        sButton.setToolTipText("");
        sButton.setBorder(null);
        sButton.setMaximumSize(new java.awt.Dimension(30, 30));
        sButton.setMinimumSize(new java.awt.Dimension(30, 30));
        sButton.setPreferredSize(new java.awt.Dimension(40, 40));
        sButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sButtonMouseClicked(evt);
            }
        });
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(kButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(eButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(mButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(uButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(zButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(oButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(iButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(qButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(aButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(wButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(xButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(yButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(vButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(qButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 255, -1, -1));

        letter1.setEditable(false);
        letter1.setBackground(java.awt.Color.gray);
        letter1.setForeground(java.awt.Color.white);
        letter1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 213, 30, 30));

        letter2.setEditable(false);
        letter2.setBackground(java.awt.Color.gray);
        letter2.setForeground(java.awt.Color.white);
        letter2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 213, 30, 30));

        letter3.setEditable(false);
        letter3.setBackground(java.awt.Color.gray);
        letter3.setForeground(java.awt.Color.white);
        letter3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 213, 30, 30));

        letter4.setEditable(false);
        letter4.setBackground(java.awt.Color.gray);
        letter4.setForeground(java.awt.Color.white);
        letter4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 213, 30, 30));

        letter5.setEditable(false);
        letter5.setBackground(java.awt.Color.gray);
        letter5.setForeground(java.awt.Color.white);
        letter5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 213, 30, 30));

        letter6.setEditable(false);
        letter6.setBackground(java.awt.Color.gray);
        letter6.setForeground(java.awt.Color.white);
        letter6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 213, 30, 30));

        letter7.setEditable(false);
        letter7.setBackground(java.awt.Color.gray);
        letter7.setForeground(java.awt.Color.white);
        letter7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 213, 30, 30));

        letter8.setEditable(false);
        letter8.setBackground(java.awt.Color.gray);
        letter8.setForeground(java.awt.Color.white);
        letter8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 213, 30, 30));

        letter9.setEditable(false);
        letter9.setBackground(java.awt.Color.gray);
        letter9.setForeground(java.awt.Color.white);
        letter9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 213, 30, 30));

        letter10.setEditable(false);
        letter10.setBackground(java.awt.Color.gray);
        letter10.setForeground(java.awt.Color.white);
        letter10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 213, 30, 30));

        letter11.setEditable(false);
        letter11.setBackground(java.awt.Color.gray);
        letter11.setForeground(java.awt.Color.white);
        letter11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 213, 30, 30));

        mistakeCounter.setForeground(java.awt.Color.white);
        mistakeCounter.setText("Mistakes: 0");
        getContentPane().add(mistakeCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        letter12.setEditable(false);
        letter12.setBackground(java.awt.Color.gray);
        letter12.setForeground(java.awt.Color.white);
        letter12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter12, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 213, 30, 30));

        letter13.setEditable(false);
        letter13.setBackground(java.awt.Color.gray);
        letter13.setForeground(java.awt.Color.white);
        letter13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letter13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letter13, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 213, 30, 30));

        leaderboard.setForeground(java.awt.Color.white);
        leaderboard.setText("Leaderboard");

        username.setForeground(java.awt.Color.white);
        username.setText("Username: ");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        usernameInput.setBackground(java.awt.Color.gray);
        usernameInput.setBorder(null);
        usernameInput.setForeground(java.awt.Color.white);
        jScrollPane2.setViewportView(usernameInput);

        submit.setBackground(java.awt.Color.black);
        submit.setForeground(java.awt.Color.white);
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameEndLayout = new javax.swing.GroupLayout(gameEnd);
        gameEnd.setLayout(gameEndLayout);
        gameEndLayout.setHorizontalGroup(
            gameEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameEndLayout.createSequentialGroup()
                .addGroup(gameEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameEndLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(leaderboard))
                    .addGroup(gameEndLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameEndLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(submit)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        gameEndLayout.setVerticalGroup(
            gameEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leaderboard)
                .addGap(18, 18, 18)
                .addGroup(gameEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addGap(71, 71, 71))
        );

        getContentPane().add(gameEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 6, -1, 189));

        stats.setColumns(20);
        stats.setForeground(java.awt.Color.white);
        stats.setRows(5);
        stats.setOpaque(false);
        stats.setPreferredSize(new java.awt.Dimension(175, 84));

        endText.setForeground(java.awt.Color.white);
        endText.setText("jLabel1");

        javax.swing.GroupLayout endScreenLayout = new javax.swing.GroupLayout(endScreen);
        endScreen.setLayout(endScreenLayout);
        endScreenLayout.setHorizontalGroup(
            endScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endScreenLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(endText)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(endScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endScreenLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        endScreenLayout.setVerticalGroup(
            endScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endText)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(endScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endScreenLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        getContentPane().add(endScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, -1, -1));

        homeButton.setBackground(java.awt.Color.black);
        homeButton.setForeground(java.awt.Color.white);
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));
        getContentPane().add(hangedMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 235, 195));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        game.this.dispose();
        setup config = new setup();
        config.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        game.this.dispose();
        homeScreen home = new homeScreen();
        home.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        submit.setEnabled(false);
        String newLine= usernameInput.getText().replace(" ", "_")+" "+String.valueOf(guessCount)+" "+String.valueOf(mistakeCount)+" "+String.valueOf(guessCount-mistakeCount)+" "+String.valueOf(wordLength);
        try{
            FileWriter myWriter = new FileWriter("files/leaderboard.txt", true);
            myWriter.write("\n"+newLine);
            myWriter.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void qButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[16]) {
            qButton.setEnabled(!qButton.isEnabled());
        }
    }//GEN-LAST:event_qButtonMouseClicked

    private void wButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[22]) {
            wButton.setEnabled(!wButton.isEnabled());
        }
    }//GEN-LAST:event_wButtonMouseClicked

    private void eButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[4]) {
            eButton.setEnabled(!eButton.isEnabled());
        }
    }//GEN-LAST:event_eButtonMouseClicked

    private void rButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[17]) {
            rButton.setEnabled(!rButton.isEnabled());
        }
    }//GEN-LAST:event_rButtonMouseClicked

    private void tButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[19]) {
            tButton.setEnabled(!tButton.isEnabled());
        }
    }//GEN-LAST:event_tButtonMouseClicked

    private void yButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[24]) {
            yButton.setEnabled(!yButton.isEnabled());
        }
    }//GEN-LAST:event_yButtonMouseClicked

    private void uButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[20]) {
            uButton.setEnabled(!uButton.isEnabled());
        }
    }//GEN-LAST:event_uButtonMouseClicked

    private void iButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[8]) {
            iButton.setEnabled(!iButton.isEnabled());
        }
    }//GEN-LAST:event_iButtonMouseClicked

    private void oButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[14]) {
            oButton.setEnabled(!oButton.isEnabled());
        }
    }//GEN-LAST:event_oButtonMouseClicked

    private void pButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[15]) {
            pButton.setEnabled(!pButton.isEnabled());
        }
    }//GEN-LAST:event_pButtonMouseClicked

    private void aButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[0]) {
            aButton.setEnabled(!aButton.isEnabled());
        }
    }//GEN-LAST:event_aButtonMouseClicked

    private void sButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[18]) {
            sButton.setEnabled(!sButton.isEnabled());
        }
    }//GEN-LAST:event_sButtonMouseClicked

    private void dButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[3]) {
            dButton.setEnabled(!dButton.isEnabled());
        }
    }//GEN-LAST:event_dButtonMouseClicked

    private void fButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[5]) {
            fButton.setEnabled(!fButton.isEnabled());
        }
    }//GEN-LAST:event_fButtonMouseClicked

    private void gButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[6]) {
            gButton.setEnabled(!gButton.isEnabled());
        }
    }//GEN-LAST:event_gButtonMouseClicked

    private void hButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[7]) {
            hButton.setEnabled(!hButton.isEnabled());
        }
    }//GEN-LAST:event_hButtonMouseClicked

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[9]) {
            jButton.setEnabled(!jButton.isEnabled());
        }
    }//GEN-LAST:event_jButtonMouseClicked

    private void kButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[10]) {
            kButton.setEnabled(!kButton.isEnabled());
        }
    }//GEN-LAST:event_kButtonMouseClicked

    private void lButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[11]) {
            lButton.setEnabled(!lButton.isEnabled());
        }
    }//GEN-LAST:event_lButtonMouseClicked

    private void zButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[25]) {
            zButton.setEnabled(!zButton.isEnabled());
        }
    }//GEN-LAST:event_zButtonMouseClicked

    private void xButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[23]) {
            xButton.setEnabled(!xButton.isEnabled());
        }
    }//GEN-LAST:event_xButtonMouseClicked

    private void cButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[2]) {
            cButton.setEnabled(!cButton.isEnabled());
        }
    }//GEN-LAST:event_cButtonMouseClicked

    private void vButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[21]) {
            vButton.setEnabled(!vButton.isEnabled());
        }
    }//GEN-LAST:event_vButtonMouseClicked

    private void bButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[1]) {
            bButton.setEnabled(!bButton.isEnabled());
        }
    }//GEN-LAST:event_bButtonMouseClicked

    private void nButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[13]) {
            nButton.setEnabled(!nButton.isEnabled());
        }
    }//GEN-LAST:event_nButtonMouseClicked

    private void mButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt) && canEnable[12]) {
            mButton.setEnabled(!mButton.isEnabled());
        }
    }//GEN-LAST:event_mButtonMouseClicked

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        validLetter("q");
    }//GEN-LAST:event_qButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        validLetter("w");
    }//GEN-LAST:event_wButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        validLetter("e");
    }//GEN-LAST:event_eButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        validLetter("r");
    }//GEN-LAST:event_rButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        validLetter("t");
    }//GEN-LAST:event_tButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        validLetter("y");
    }//GEN-LAST:event_yButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        validLetter("u");
    }//GEN-LAST:event_uButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        validLetter("i");
    }//GEN-LAST:event_iButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        validLetter("o");
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        validLetter("p");
    }//GEN-LAST:event_pButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        validLetter("a");
    }//GEN-LAST:event_aButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        validLetter("s");
    }//GEN-LAST:event_sButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        validLetter("d");
    }//GEN-LAST:event_dButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        validLetter("f");
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        validLetter("g");
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        validLetter("h");
    }//GEN-LAST:event_hButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        validLetter("j");
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        validLetter("k");
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        validLetter("l");
    }//GEN-LAST:event_lButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        validLetter("z");
    }//GEN-LAST:event_zButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        validLetter("x");
    }//GEN-LAST:event_xButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        validLetter("c");
    }//GEN-LAST:event_cButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        validLetter("v");
    }//GEN-LAST:event_vButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        validLetter("b");
    }//GEN-LAST:event_bButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        validLetter("n");
    }//GEN-LAST:event_nButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        validLetter("m");
    }//GEN-LAST:event_mButtonActionPerformed

    public static void create() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
    }
     
    public void wordSelect(){
        Random rand = new Random();
        do{
            try (Stream<String> lines = Files.lines(Paths.get("files/wordList.txt"))) {
                word = (lines.skip(rand.nextInt(20000)).findFirst().get()).toLowerCase();
            }
            catch(IOException e){
                System.out.println(e);
                break;
            }
        }while(word.length()!=wordLength);
        System.out.println("Word to guess is: "+word);
        
    }
    
    public void letterSetup(){
        for(int x=12; x>=wordLength; x--){
            letters[x].setVisible(false);
        }
    }
    
    private void wordArray(){
        wordToGuess = word.split("");
    }

    private int letterToNumber(String letter){
        for(int x=0; x<=25; x++){
            if(alphabet[x].equals(letter)){
                return x;
            }
        }
        return 0;
    }
    
    private void validLetter(String guess){
        guessCount++;
        int letter =letterToNumber(guess);
        boolean correct=false;
        for(int x=0; x<wordLength; x++){
            if(wordToGuess[x].equals(guess)){
                correctLetters++;
                letters[x].setText(guess.toUpperCase());
                letterButtons[letter].setBackground(green);
                letters[x].setForeground(green);
                canEnable[letter]=false;
                correct=true;
            }
        }
        letterButtons[letter].setEnabled(false);
        if(correct){
            if(correctLetters==wordLength)
                wonGame(true);
        }
        else{
            mistakeCount++;
            canEnable[letter]=false;
            letterButtons[letter].setBackground(red);
            mistakeCounter.setText("Mistakes: "+mistakeCount);
            hangedMan.setIcon(images[mistakeCount]);
            if(mistakeCount==6)
                wonGame(false);
        }
        
    }
    
    private void wonGame(boolean win){
        for(int x=0; x<=25; x++){
            letterButtons[x].setEnabled(false);
        }
        if(win){
            endText.setText("YOU WON!!");
            stats.setText("You solved a "+wordLength+" letter long\nword with "+mistakeCount+" mistakes!");
             
        }
        else{
            endText.setText("YOU LOST!!");
            stats.setText("You failed a "+wordLength+" letter long\nword with "+correctLetters+" letter(s) correct\nand "+mistakeCount+" mistakes");
            for(int x=0; x<wordLength;x++){
                if(!letters[x].getText().toLowerCase().equals(wordToGuess[x])){
                    letters[x].setText(wordToGuess[x].toUpperCase());
                    letters[x].setForeground(red);
                };
            }    
        }
        for(int x=0; x<=25;x++)
            canEnable[x]=false;
        endScreen.setVisible(true);
        gameEnd.setVisible(true);
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aButton;
    private javax.swing.JToggleButton bButton;
    private javax.swing.JButton back;
    private javax.swing.JToggleButton cButton;
    private javax.swing.JToggleButton dButton;
    private javax.swing.JToggleButton eButton;
    private javax.swing.JPanel endScreen;
    private javax.swing.JLabel endText;
    private javax.swing.JToggleButton fButton;
    private javax.swing.JToggleButton gButton;
    private javax.swing.JPanel gameEnd;
    private javax.swing.JToggleButton hButton;
    private javax.swing.JLabel hangedMan;
    private javax.swing.JButton homeButton;
    private javax.swing.JToggleButton iButton;
    private javax.swing.JToggleButton jButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton kButton;
    private javax.swing.JToggleButton lButton;
    private javax.swing.JLabel leaderboard;
    private javax.swing.JTextField letter1;
    private javax.swing.JTextField letter10;
    private javax.swing.JTextField letter11;
    private javax.swing.JTextField letter12;
    private javax.swing.JTextField letter13;
    private javax.swing.JTextField letter2;
    private javax.swing.JTextField letter3;
    private javax.swing.JTextField letter4;
    private javax.swing.JTextField letter5;
    private javax.swing.JTextField letter6;
    private javax.swing.JTextField letter7;
    private javax.swing.JTextField letter8;
    private javax.swing.JTextField letter9;
    private javax.swing.JToggleButton mButton;
    private javax.swing.JLabel mistakeCounter;
    private javax.swing.JToggleButton nButton;
    private javax.swing.JToggleButton oButton;
    private javax.swing.JToggleButton pButton;
    private javax.swing.JToggleButton qButton;
    private javax.swing.JToggleButton rButton;
    private javax.swing.JToggleButton sButton;
    private javax.swing.JTextArea stats;
    private javax.swing.JButton submit;
    private javax.swing.JToggleButton tButton;
    private javax.swing.JToggleButton uButton;
    private javax.swing.JLabel username;
    private javax.swing.JTextPane usernameInput;
    private javax.swing.JToggleButton vButton;
    private javax.swing.JToggleButton wButton;
    private javax.swing.JToggleButton xButton;
    private javax.swing.JToggleButton yButton;
    private javax.swing.JToggleButton zButton;
    // End of variables declaration//GEN-END:variables
}